/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, {useEffect, useRef} from 'react';
import {useGLTF, useAnimations} from '@react-three/drei/native';
import {GLTF} from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    vanguard_Mesh: THREE.SkinnedMesh;
    vanguard_visor: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    VanguardBodyMat: THREE.MeshPhysicalMaterial;
    Vanguard_VisorMat: THREE.MeshPhysicalMaterial;
  };
};

/**
 *  For some reason it is not possible to use '@react-three/drei/native' and
 *  'expo-three' at the same time in a project. We will receive an error that
 *  document does not exist. Separately, these libraries work correctly.
 *  Until the problem is resolved, you should be aware of this when designing
 *  new applications using 3D graphics
 */
export default function Solider(props: JSX.IntrinsicElements['group']) {
  const ActionName = 'Armature|mixamo.com|Layer0';
  const group = useRef<THREE.Group>(null);
  const {nodes, materials, animations} = useGLTF(
    require('../assets/models/solider/solider.glb'),
  ) as GLTFResult;

  const {actions} = useAnimations(animations, group);
  useEffect(() => {
    actions[ActionName]?.play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" scale={0.2} position={[0, 0, -2]}>
        <group
          name="Armature"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
          position={[0, -1.5, 0]}>
          <skinnedMesh
            name="vanguard_Mesh"
            geometry={nodes.vanguard_Mesh.geometry}
            material={materials.VanguardBodyMat}
            skeleton={nodes.vanguard_Mesh.skeleton}
          />
          <skinnedMesh
            name="vanguard_visor"
            geometry={nodes.vanguard_visor.geometry}
            material={materials.Vanguard_VisorMat}
            skeleton={nodes.vanguard_visor.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(require('../assets/models/solider/solider.glb'));
